#!/bin/sh
# Xsetup - run as root before the login dialog appears

#iGPU
xrandr --output DisplayPort-1-3 --off
xrandr --output HDMI-A-1-1 --off

#dGPU
xrandr --output DisplayPort-1 --off
xrandr --output DisplayPort-2 --off
xrandr --output HDMI-A-0 --off